# Generated by Django 5.0 on 2024-01-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile_country_profile_date_of_birth_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('public_user', 'User'), ('vendor', 'Vendor'), ('admin', 'Admin'), ('staff', 'Staff')], max_length=255, null=True),
        ),
    ]
