# Generated by Django 5.0 on 2024-02-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='attachments'),
        ),
        migrations.AddField(
            model_name='profile',
            name='title_for_staff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
