# Generated by Django 5.0 on 2024-02-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_profile_profile_picture_profile_title_for_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
