# Generated by Django 5.0 on 2024-02-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_remove_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("public_user", "User"),
                    ("vendor", "Vendor"),
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                    ("place_staff", "Place Staff"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
