# Generated by Django 5.0 on 2024-02-06 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_profile_role"),
        ("v1", "0016_remove_place_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="staff",
                to="v1.place",
            ),
        ),
    ]
