# Generated by Django 5.0 on 2024-01-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_place_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='address',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='address',
            name='site_url',
            field=models.URLField(blank=True, null=True, verbose_name='External URL'),
        ),
    ]
