# Generated by Django 5.0 on 2024-01-23 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_address_contact_email_address_contact_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityplan',
            name='number_of_people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActivityPlanJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Instance Active')),
                ('udf_1', models.CharField(blank=True, max_length=255, null=True)),
                ('udf_2', models.CharField(blank=True, max_length=255, null=True)),
                ('udf_3', models.CharField(blank=True, max_length=255, null=True)),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Is Accepted by Planner')),
                ('joining_request_date', models.DateTimeField(blank=True, null=True, verbose_name='Joining Request Date')),
                ('joining_accept_date', models.DateTimeField(blank=True, null=True, verbose_name='Joining Acceptance Date')),
                ('join_date', models.DateTimeField(blank=True, null=True, verbose_name='Plan Joining Date of user')),
                ('activity_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.activityplan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Plan Join',
                'verbose_name_plural': 'Activity Plan Joins',
            },
        ),
        migrations.AddField(
            model_name='activityplan',
            name='joinies',
            field=models.ManyToManyField(blank=True, related_name='joined_plans', through='v1.ActivityPlanJoin', to=settings.AUTH_USER_MODEL),
        ),
    ]
