# Generated by Django 5.0 on 2024-02-01 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_activity_icon_transporttype_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='attachmentgroup',
            name='place',
        ),
        migrations.RemoveField(
            model_name='qagroup',
            name='place',
        ),
        migrations.RemoveField(
            model_name='transporttype',
            name='icon',
        ),
        migrations.AddField(
            model_name='attachment',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='icons', to='v1.activity'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='transport_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='icons', to='v1.transporttype'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_pics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachmentgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qagroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
