# Generated by Django 5.0 on 2024-02-04 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0011_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='v1.attachmentgroup'),
        ),
        migrations.AlterField(
            model_name='qaitem',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='v1.qagroup'),
        ),
    ]
