# Generated by Django 5.0 on 2024-02-05 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0012_alter_attachment_group_alter_qaitem_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="staff",
            field=models.ManyToManyField(
                blank=True, related_name="places", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
