# Generated by Django 5.0 on 2024-02-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0013_place_staff"),
        ("v1", "0014_alter_bookmark_place_alter_bookmark_user"),
    ]

    operations = []
