# Generated by Django 5.0 on 2024-02-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0015_merge_20240206_1730"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="staff",
        ),
    ]
