# Generated by Django 5.0 on 2024-02-20 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0017_menu_attachment_menu_menucategory_menu_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="atmosphere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="icons",
                to="v1.atmosphere",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="group_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="icons",
                to="v1.grouptype",
            ),
        ),
    ]
